# Generated by Django 6.0.4 on 2026-04-19 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('status', models.BooleanField(default=True)),
                ('civilian_id_card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('police_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('id_image_front', models.ImageField(blank=True, null=True, upload_to='id/')),
                ('id_image_back', models.ImageField(blank=True, null=True, upload_to='id/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authentication', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
