# Generated by Django 6.0.4 on 2026-04-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='police_id_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
