# Generated by Django 6.0.4 on 2026-04-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Civilian_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='violations',
            field=models.CharField(max_length=50),
        ),
    ]
