# Generated by Django 6.0.4 on 2026-04-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Civilian_User', '0002_alter_evidence_violations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='evidence',
            name='violations',
            field=models.TextField(),
        ),
    ]
