# Generated by Django 6.0.4 on 2026-04-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Civilian_User', '0003_remove_evidence_created_at_alter_evidence_violations'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='complaint_seq',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evidence',
            name='violations',
            field=models.CharField(max_length=50),
        ),
    ]
